2021-06-30 16:46:59,805 INFO    MainThread:21184 [internal.py:wandb_internal():91] W&B internal server running at pid: 21184, started at: 2021-06-30 16:46:59.797730
2021-06-30 16:46:59,807 INFO    WriterThread:21184 [datastore.py:open_for_write():80] open: C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_164644-6o0jurm8\run-6o0jurm8.wandb
2021-06-30 16:46:59,809 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: check_version
2021-06-30 16:46:59,812 DEBUG   SenderThread:21184 [sender.py:send():179] send: header
2021-06-30 16:46:59,813 DEBUG   SenderThread:21184 [sender.py:send_request():193] send_request: check_version
2021-06-30 16:47:00,555 DEBUG   SenderThread:21184 [sender.py:send():179] send: run
2021-06-30 16:47:01,023 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: run_start
2021-06-30 16:47:01,066 INFO    SenderThread:21184 [dir_watcher.py:__init__():168] watching files in: C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_164644-6o0jurm8\files
2021-06-30 16:47:01,066 INFO    SenderThread:21184 [sender.py:_start_run_threads():707] run started: 6o0jurm8 with start time 1625064415
2021-06-30 16:47:01,066 DEBUG   SenderThread:21184 [sender.py:send():179] send: summary
2021-06-30 16:47:01,067 INFO    SenderThread:21184 [sender.py:_save_file():829] saving file wandb-summary.json with policy end
2021-06-30 16:47:01,675 DEBUG   HandlerThread:21184 [meta.py:__init__():39] meta init
2021-06-30 16:47:01,675 DEBUG   HandlerThread:21184 [meta.py:__init__():53] meta init done
2021-06-30 16:47:01,675 DEBUG   HandlerThread:21184 [meta.py:probe():210] probe
2021-06-30 16:47:01,684 DEBUG   HandlerThread:21184 [meta.py:_setup_git():200] setup git
2021-06-30 16:47:01,817 DEBUG   HandlerThread:21184 [meta.py:_setup_git():207] setup git done
2021-06-30 16:47:01,817 DEBUG   HandlerThread:21184 [meta.py:_save_pip():57] save pip
2021-06-30 16:47:01,818 DEBUG   HandlerThread:21184 [meta.py:_save_pip():71] save pip done
2021-06-30 16:47:01,819 DEBUG   HandlerThread:21184 [meta.py:_save_conda():78] save conda
2021-06-30 16:47:01,847 ERROR   HandlerThread:21184 [meta.py:_save_conda():85] Error saving conda packages
Traceback (most recent call last):
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\wandb\sdk\internal\meta.py", line 83, in _save_conda
    subprocess.call(["conda", "env", "export"], stdout=f)
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
2021-06-30 16:47:01,883 DEBUG   HandlerThread:21184 [meta.py:_save_conda():86] save conda done
2021-06-30 16:47:01,883 DEBUG   HandlerThread:21184 [meta.py:probe():252] probe done
2021-06-30 16:47:01,911 DEBUG   SenderThread:21184 [sender.py:send():179] send: files
2021-06-30 16:47:01,911 INFO    SenderThread:21184 [sender.py:_save_file():829] saving file wandb-metadata.json with policy now
2021-06-30 16:47:01,919 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: stop_status
2021-06-30 16:47:01,920 DEBUG   SenderThread:21184 [sender.py:send_request():193] send_request: stop_status
2021-06-30 16:47:02,068 INFO    Thread-12 :21184 [dir_watcher.py:_on_file_created():216] file/dir created: C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_164644-6o0jurm8\files\requirements.txt
2021-06-30 16:47:02,069 INFO    Thread-12 :21184 [dir_watcher.py:_on_file_created():216] file/dir created: C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_164644-6o0jurm8\files\wandb-metadata.json
2021-06-30 16:47:02,069 INFO    Thread-12 :21184 [dir_watcher.py:_on_file_created():216] file/dir created: C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_164644-6o0jurm8\files\conda-environment.yaml
2021-06-30 16:47:02,070 INFO    Thread-12 :21184 [dir_watcher.py:_on_file_created():216] file/dir created: C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_164644-6o0jurm8\files\wandb-summary.json
2021-06-30 16:47:02,070 INFO    Thread-12 :21184 [dir_watcher.py:_on_file_created():216] file/dir created: C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_164644-6o0jurm8\files\output.log
2021-06-30 16:47:02,789 INFO    Thread-17 :21184 [upload_job.py:push():133] Uploaded file C:\Users\ABHISH~1\AppData\Local\Temp\tmpk94xdbw_wandb\quzk5z57-wandb-metadata.json
2021-06-30 16:47:03,645 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: pause
2021-06-30 16:47:03,645 INFO    HandlerThread:21184 [handler.py:handle_request_pause():525] stopping system metrics thread
2021-06-30 16:47:03,749 DEBUG   SenderThread:21184 [sender.py:send():179] send: stats
2021-06-30 16:47:04,071 INFO    Thread-12 :21184 [dir_watcher.py:_on_file_modified():229] file/dir modified: C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_164644-6o0jurm8\files\output.log
2021-06-30 16:47:17,194 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: stop_status
2021-06-30 16:47:17,194 DEBUG   SenderThread:21184 [sender.py:send_request():193] send_request: stop_status
2021-06-30 16:47:32,465 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: stop_status
2021-06-30 16:47:32,466 DEBUG   SenderThread:21184 [sender.py:send_request():193] send_request: stop_status
2021-06-30 16:47:36,301 ERROR   FileStreamThread:21184 [file_stream.py:_thread_except_body():293] generic exception in filestream thread
Traceback (most recent call last):
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\wandb\sdk\internal\file_stream.py", line 289, in _thread_except_body
    self._thread_body()
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\wandb\sdk\internal\file_stream.py", line 276, in _thread_body
    json={"complete": False, "failed": False},
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\wandb\sdk\internal\file_stream.py", line 302, in _handle_response
    raise response
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\wandb\sdk\internal\file_stream.py", line 392, in request_with_retry
    response.raise_for_status()
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/abhishekdiphu/visualize-sklearn/6o0jurm8/file_stream
2021-06-30 16:47:40,914 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: resume
2021-06-30 16:47:40,914 INFO    HandlerThread:21184 [handler.py:handle_request_resume():520] starting system metrics thread
2021-06-30 16:47:41,234 INFO    Thread-12 :21184 [dir_watcher.py:_on_file_modified():229] file/dir modified: C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_164644-6o0jurm8\files\output.log
2021-06-30 16:47:41,702 DEBUG   SenderThread:21184 [sender.py:send():179] send: telemetry
2021-06-30 16:47:41,702 DEBUG   SenderThread:21184 [sender.py:send():179] send: exit
2021-06-30 16:47:41,702 INFO    SenderThread:21184 [sender.py:send_exit():287] handling exit code: 0
2021-06-30 16:47:41,702 INFO    SenderThread:21184 [sender.py:send_exit():295] send defer
2021-06-30 16:47:41,702 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: poll_exit
2021-06-30 16:47:41,702 DEBUG   SenderThread:21184 [sender.py:send_request():193] send_request: poll_exit
2021-06-30 16:47:41,702 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: defer
2021-06-30 16:47:41,702 INFO    HandlerThread:21184 [handler.py:handle_request_defer():141] handle defer: 0
2021-06-30 16:47:41,702 DEBUG   SenderThread:21184 [sender.py:send_request():193] send_request: defer
2021-06-30 16:47:41,702 INFO    SenderThread:21184 [sender.py:send_request_defer():304] handle sender defer: 0
2021-06-30 16:47:41,702 INFO    SenderThread:21184 [sender.py:send_request_defer():342] send defer: 1
2021-06-30 16:47:41,702 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: defer
2021-06-30 16:47:41,702 INFO    HandlerThread:21184 [handler.py:handle_request_defer():141] handle defer: 1
2021-06-30 16:47:41,748 DEBUG   SenderThread:21184 [sender.py:send_request():193] send_request: defer
2021-06-30 16:47:41,748 INFO    SenderThread:21184 [sender.py:send_request_defer():304] handle sender defer: 1
2021-06-30 16:47:41,748 INFO    SenderThread:21184 [sender.py:send_request_defer():342] send defer: 2
2021-06-30 16:47:41,748 DEBUG   SenderThread:21184 [sender.py:send():179] send: stats
2021-06-30 16:47:41,748 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: defer
2021-06-30 16:47:41,748 INFO    HandlerThread:21184 [handler.py:handle_request_defer():141] handle defer: 2
2021-06-30 16:47:41,748 DEBUG   SenderThread:21184 [sender.py:send_request():193] send_request: defer
2021-06-30 16:47:41,748 INFO    SenderThread:21184 [sender.py:send_request_defer():304] handle sender defer: 2
2021-06-30 16:47:41,748 INFO    SenderThread:21184 [sender.py:send_request_defer():342] send defer: 3
2021-06-30 16:47:41,748 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: defer
2021-06-30 16:47:41,748 INFO    HandlerThread:21184 [handler.py:handle_request_defer():141] handle defer: 3
2021-06-30 16:47:41,748 DEBUG   SenderThread:21184 [sender.py:send():179] send: summary
2021-06-30 16:47:41,748 INFO    SenderThread:21184 [sender.py:_save_file():829] saving file wandb-summary.json with policy end
2021-06-30 16:47:41,748 DEBUG   SenderThread:21184 [sender.py:send_request():193] send_request: defer
2021-06-30 16:47:41,748 INFO    SenderThread:21184 [sender.py:send_request_defer():304] handle sender defer: 3
2021-06-30 16:47:41,748 INFO    SenderThread:21184 [sender.py:send_request_defer():342] send defer: 4
2021-06-30 16:47:41,748 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: defer
2021-06-30 16:47:41,748 INFO    HandlerThread:21184 [handler.py:handle_request_defer():141] handle defer: 4
2021-06-30 16:47:41,764 DEBUG   SenderThread:21184 [sender.py:send_request():193] send_request: defer
2021-06-30 16:47:41,764 INFO    SenderThread:21184 [sender.py:send_request_defer():304] handle sender defer: 4
2021-06-30 16:47:41,811 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: poll_exit
2021-06-30 16:47:42,238 INFO    Thread-12 :21184 [dir_watcher.py:_on_file_modified():229] file/dir modified: C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_164644-6o0jurm8\files\wandb-summary.json
2021-06-30 16:47:42,238 INFO    Thread-12 :21184 [dir_watcher.py:_on_file_modified():229] file/dir modified: C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_164644-6o0jurm8\files\output.log
2021-06-30 16:47:42,442 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 16:47:42,473 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 16:47:43,773 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 16:47:43,773 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 16:47:46,499 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 16:47:46,499 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 16:47:46,499 ERROR   SenderThread:21184 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\wandb\sdk\internal\internal_api.py", line 133, in execute
    six.reraise(*sys.exc_info())
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\wandb\sdk\internal\internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 39, in execute
    request.raise_for_status()
  File "C:\Users\abhishek buragohaibn\Anaconda3\envs\computervison\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2021-06-30 16:47:46,912 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: poll_exit
2021-06-30 16:47:51,886 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 16:47:51,886 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 16:47:52,023 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: poll_exit
2021-06-30 16:47:57,135 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: poll_exit
2021-06-30 16:48:02,040 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 16:48:02,040 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 16:48:02,259 DEBUG   HandlerThread:21184 [handler.py:handle_request():124] handle_request: poll_exit
2021-06-30 16:48:19,734 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 16:48:19,734 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 16:48:53,089 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 16:48:53,089 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 16:49:59,416 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 16:49:59,416 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 16:52:15,791 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 16:52:15,792 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 16:56:49,223 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 16:56:49,224 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 17:01:51,335 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 17:01:51,335 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 17:07:32,088 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 17:07:32,088 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 17:13:40,453 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 17:13:40,453 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 17:19:26,514 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 17:19:26,514 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 17:24:38,849 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 17:24:39,012 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 17:30:48,108 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 17:30:48,108 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 17:36:48,870 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 17:36:48,947 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 17:42:58,737 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 17:42:58,745 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 17:49:08,876 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 17:49:08,985 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 17:55:14,753 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 17:55:14,800 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 18:01:28,912 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 18:01:29,068 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 18:07:43,024 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 18:07:43,024 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 18:13:30,955 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 18:13:30,955 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 18:19:31,923 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 18:19:31,923 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 18:24:47,879 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 18:24:47,880 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 18:30:47,022 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 18:30:47,022 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 18:36:53,935 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 18:36:53,936 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 18:42:43,243 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 18:42:43,243 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 18:48:00,760 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 18:48:00,760 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 18:53:17,146 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 18:53:17,286 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 18:58:28,055 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 18:58:28,227 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 19:03:40,391 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 19:03:40,391 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 19:09:44,495 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 19:09:44,635 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 19:15:17,994 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 19:15:17,994 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 19:21:01,270 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 19:21:01,270 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 19:26:18,123 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 19:26:18,123 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 19:31:40,485 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 19:31:40,486 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 19:36:53,456 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 19:36:53,471 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 19:42:33,683 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 19:42:33,777 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 19:48:07,064 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 19:48:07,065 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 19:54:16,114 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 19:54:16,114 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 19:59:41,322 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 19:59:41,322 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 20:05:14,031 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 20:05:14,032 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 20:10:35,176 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 20:10:35,176 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 20:54:07,797 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 20:54:07,797 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 20:59:10,762 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 20:59:10,762 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 21:05:12,465 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 21:05:12,465 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 21:11:24,853 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 21:11:24,853 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 21:16:56,283 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 21:16:56,284 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 21:22:00,498 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 21:22:00,499 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 21:27:43,925 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 21:27:43,926 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 21:33:30,836 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 21:33:30,836 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 21:38:49,250 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 21:38:49,250 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 21:45:00,653 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 21:45:00,653 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 21:51:03,284 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 21:51:03,285 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 21:56:12,897 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 21:56:12,897 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 22:01:31,773 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 22:01:31,773 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 22:06:36,481 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 22:06:36,481 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 22:12:12,508 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 22:12:12,508 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 22:17:47,334 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 22:17:47,335 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 22:23:04,642 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 22:23:04,642 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 22:28:41,549 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 22:28:41,549 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 22:34:17,408 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 22:34:17,408 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 22:39:46,536 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 22:39:46,536 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 22:45:08,154 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 22:45:08,154 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 22:51:01,962 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 22:51:01,963 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 22:56:29,959 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 22:56:29,960 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 23:01:49,637 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 23:01:49,638 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 23:07:07,911 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 23:07:07,911 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 23:12:23,471 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 23:12:23,472 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 23:18:05,456 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 23:18:05,457 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 23:23:31,909 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 23:23:31,909 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 23:25:01,435 WARNING MainThread:21184 [internal.py:is_dead():367] Internal process exiting, parent pid 14312 disappeared
2021-06-30 23:25:01,435 ERROR   MainThread:21184 [internal.py:wandb_internal():143] Internal process shutdown.
2021-06-30 23:25:01,435 INFO    HandlerThread:21184 [handler.py:finish():638] shutting down handler
2021-06-30 23:25:02,436 INFO    WriterThread:21184 [datastore.py:close():288] close: C:\Users\abhishek buragohaibn\Desktop\COURSERA\IBM_AI_Enterprise_Workflow\AI_capstone\solution-guidance\wandb\run-20210630_164644-6o0jurm8\run-6o0jurm8.wandb
2021-06-30 23:28:40,962 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 23:28:40,963 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 23:34:05,298 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 23:34:05,298 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 23:39:21,203 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 23:39:21,203 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 23:45:27,993 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 23:45:27,993 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-06-30 23:50:42,321 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-06-30 23:50:42,321 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 01:50:57,368 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 01:50:57,368 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 01:56:33,672 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 01:56:33,672 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 02:01:44,358 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 02:01:44,358 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 02:06:54,621 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 02:06:54,622 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 02:12:22,552 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 02:12:22,552 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 02:18:24,644 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 02:18:24,645 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 02:23:26,957 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 02:23:26,957 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 02:28:41,383 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 02:28:41,383 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 02:34:24,642 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 02:34:24,643 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 02:40:13,958 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 02:40:13,959 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 03:50:03,095 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 03:50:03,096 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 03:55:12,330 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 03:55:12,330 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 04:00:43,492 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 04:00:43,493 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 04:05:59,769 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 04:05:59,769 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 04:12:08,086 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 04:12:08,086 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 04:17:58,674 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 04:17:58,674 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 04:23:44,516 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 04:23:44,516 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 09:31:24,084 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 09:31:24,084 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 09:37:37,856 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 09:37:37,856 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 09:43:20,333 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 09:43:20,333 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 09:49:16,975 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 09:49:17,163 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 09:54:50,166 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 09:54:50,166 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 10:00:12,100 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 10:00:12,100 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 10:05:34,576 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 10:05:34,576 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 10:11:46,391 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 10:11:46,392 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 10:17:15,525 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 10:17:15,525 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 10:22:45,813 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 10:22:45,814 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 10:34:28,911 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 10:34:28,911 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 10:40:31,765 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 10:40:31,766 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 10:46:32,579 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 10:46:32,579 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 10:52:45,624 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 10:52:45,624 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 10:57:53,107 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 10:57:53,108 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 11:03:47,859 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 11:03:47,860 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 11:09:18,016 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 11:09:18,016 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 11:14:37,181 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 11:14:37,181 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 11:20:52,123 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 11:20:52,123 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 11:26:32,113 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 11:26:32,113 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 11:31:47,526 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 11:31:47,526 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 11:37:22,972 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 11:37:22,972 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 11:42:32,379 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 11:42:32,395 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 11:48:15,022 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 11:48:15,022 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 11:53:59,190 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 11:53:59,190 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 11:59:16,183 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 11:59:16,199 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 12:04:54,072 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 12:04:54,072 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 12:10:01,724 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 12:10:01,849 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 12:15:23,810 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 12:15:23,811 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 12:21:35,384 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 12:21:35,384 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 12:26:59,520 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 12:26:59,521 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 12:33:09,262 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 12:33:09,263 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 12:39:22,355 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 12:39:22,355 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 12:45:01,990 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 12:45:01,991 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 12:51:09,424 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 12:51:09,424 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 12:57:15,860 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 12:57:15,860 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 13:02:53,856 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 13:02:53,856 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 13:08:03,871 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 13:08:03,871 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 13:13:14,687 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 13:13:14,687 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 13:19:13,442 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 13:19:13,442 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 13:24:16,028 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 13:24:16,029 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 13:29:45,269 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 13:29:45,269 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 13:35:43,512 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 13:35:43,513 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 13:41:30,807 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 13:41:30,807 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 13:47:07,496 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 13:47:07,496 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 13:52:58,588 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 13:52:58,589 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 14:10:19,090 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 14:10:19,091 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 14:16:09,614 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 14:16:09,615 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 14:21:40,140 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 14:21:40,140 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 14:27:24,517 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 14:27:24,517 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 14:33:12,302 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 14:33:12,302 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 14:39:10,307 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 14:39:10,307 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 14:45:02,848 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 14:45:02,848 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 14:50:08,237 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 14:50:08,237 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 14:56:10,781 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 14:56:10,781 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 15:01:30,637 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 15:01:30,638 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 15:07:12,871 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 15:07:12,871 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 15:12:45,319 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 15:12:45,320 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 15:18:16,138 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 15:18:16,138 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 15:23:54,324 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 15:23:54,324 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 15:28:58,190 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 15:28:58,190 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 15:34:40,819 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 15:34:40,820 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 15:39:51,793 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 15:39:51,794 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 15:45:06,558 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 15:45:06,558 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 15:51:02,297 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 15:51:02,407 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 15:56:09,868 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 15:56:09,868 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 16:02:13,096 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 16:02:13,096 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 16:08:17,090 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 16:08:17,091 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 16:14:20,494 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 16:14:20,495 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 16:20:15,530 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 16:20:15,530 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 16:25:54,339 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 16:25:54,340 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 16:31:25,069 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 16:31:25,069 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 16:37:05,183 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 16:37:05,183 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 16:42:14,360 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 16:42:14,360 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 16:47:54,249 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 16:47:54,249 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 16:53:08,703 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 16:53:08,704 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 16:58:10,945 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 16:58:11,067 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 17:03:17,391 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 17:03:17,391 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 17:08:24,795 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 17:08:24,937 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-07-01 17:13:40,597 ERROR   SenderThread:21184 [internal_api.py:execute():130] 409 response executing GraphQL.
2021-07-01 17:13:40,597 ERROR   SenderThread:21184 [internal_api.py:execute():131] {"errors":[{"message":"Error 1062: Duplicate entry '364422-6o0jurm8' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
